---
micronaut:
    application:
        name: clubs
---
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
dataSource:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''
---
consul:
  client:
    registration:
      enabled: true
      fail-fast: false
      retry-count: 10
      retry-delay: 5s
    defaultZone:  "${CONSUL_HOST:192.168.16.15}:${CONSUL_PORT:8500}"

